-- College Life Simulator — Permanent Event Definition Seeds
-- Run this after schema.sql in the Supabase SQL Editor

INSERT INTO public_event_defs (
  id,
  title,
  description,
  effect_type,
  flat_stat_changes,
  multipliers,
  metadata
) VALUES
  ('PUB-001', 'Heatwave', 'The campus turns into a brick oven, everyone is sticky, and physical activity becomes a much worse idea than usual.', 'action_multiplier', '{}'::jsonb, '{"exercise": 0.5}'::jsonb, '{"theme": "weather"}'::jsonb),
  ('PUB-002', 'Cram Season', 'Every table in the library is full, every laptop has thirty tabs open, and panic is somehow productive for once.', 'action_multiplier', '{}'::jsonb, '{"study": 1.5}'::jsonb, '{"theme": "academics"}'::jsonb),
  ('PUB-003', 'Frat Row Block Party', 'The bass is shaking the windows and nobody on campus is pretending to work after dark.', 'slot_multiplier', '{}'::jsonb, '{"night_socialize": 1.5}'::jsonb, '{"theme": "social"}'::jsonb),
  ('PUB-004', 'Campus Power Outage', 'Half the buildings lose power, half the students give up, and the rest try to study by phone flashlight.', 'slot_multiplier', '{}'::jsonb, '{"morning_study": 0.5}'::jsonb, '{"theme": "disruption"}'::jsonb),
  ('PUB-005', 'Hiring Spree', 'Every cafe and desk on campus suddenly has a help wanted sign taped to it.', 'action_multiplier', '{}'::jsonb, '{"work": 1.5}'::jsonb, '{"theme": "money"}'::jsonb),
  ('PUB-006', 'Wellness Week', 'The university spends a little money pretending to care and, surprisingly, some of it helps.', 'action_multiplier', '{}'::jsonb, '{"rest": 1.5, "sleep": 1.5}'::jsonb, '{"theme": "wellbeing"}'::jsonb),
  ('PUB-007', 'Snow Day', 'The sidewalks disappear under snow and enough professors give up that the whole day softens.', 'mixed', '{}'::jsonb, '{"class": 0.0, "rest": 1.25}'::jsonb, '{"theme": "weather", "classes_cancelled": true}'::jsonb),
  ('PUB-008', 'Flu Outbreak', 'Everyone on campus is coughing into their sleeves and pretending they are fine.', 'daily_decay', '{"wellbeing": -0.5}'::jsonb, '{}'::jsonb, '{"theme": "health"}'::jsonb),
  ('PUB-009', 'Career Fair', 'The student center fills with recruiters, lanyards, and overprepared upperclassmen trying to look calm.', 'mixed', '{"academics": 0.25}'::jsonb, '{"work": 1.25}'::jsonb, '{"theme": "career"}'::jsonb),
  ('PUB-010', 'Coffee Shop Promo', 'The campus cafe runs a study-night special and suddenly everyone is pretending caffeine counts as resilience.', 'mixed', '{"money": 0.25}'::jsonb, '{"study": 1.25}'::jsonb, '{"theme": "study"}'::jsonb),
  ('PUB-011', 'Open Mic Night', 'A lot of students who should not be brave tonight decide that they are.', 'action_multiplier', '{}'::jsonb, '{"socialize": 1.25}'::jsonb, '{"theme": "performance"}'::jsonb),
  ('PUB-012', 'Pop Quiz Panic', 'Every class rumor suddenly sounds possible and nobody feels safe.', 'daily_decay', '{"wellbeing": -0.25}'::jsonb, '{}'::jsonb, '{"theme": "academics"}'::jsonb),
  ('PUB-013', 'Free Breakfast', 'For one morning, the school accidentally solves a real problem for students.', 'mixed', '{"money": 0.5, "wellbeing": 0.25}'::jsonb, '{}'::jsonb, '{"theme": "food"}'::jsonb),
  ('PUB-014', 'Student Election Week', 'Everyone with a clipboard becomes intense and weirdly optimistic.', 'mixed', '{"social": 0.25}'::jsonb, '{"socialize": 1.25}'::jsonb, '{"theme": "campus politics"}'::jsonb),
  ('PUB-015', 'Library Flooding', 'A busted pipe knocks out part of the library and drags everyone''s focus down with it.', 'action_multiplier', '{}'::jsonb, '{"study": 0.75}'::jsonb, '{"theme": "disruption"}'::jsonb),
  ('PUB-016', 'Guest Lecture', 'A visiting speaker makes class weirdly worthwhile for one day.', 'mixed', '{"academics": 0.25, "social": 0.25}'::jsonb, '{"class": 1.25}'::jsonb, '{"theme": "academics"}'::jsonb),
  ('PUB-017', 'Campus Fun Run', 'The rec center guilts everyone into pretending movement is joy.', 'mixed', '{"social": 0.25}'::jsonb, '{"exercise": 1.25}'::jsonb, '{"theme": "fitness"}'::jsonb),
  ('PUB-018', 'Tuition Panic', 'Someone posts about fees, debt, and payment deadlines, and suddenly everyone remembers adulthood is real.', 'daily_decay', '{"money": -0.25}'::jsonb, '{}'::jsonb, '{"theme": "money"}'::jsonb),
  ('PUB-019', 'Volunteer Fair', 'Campus gets aggressively wholesome for a day and people feel a little better about themselves because of it.', 'mixed', '{"wellbeing": 0.25, "social": 0.25}'::jsonb, '{}'::jsonb, '{"theme": "community"}'::jsonb),
  ('PUB-020', 'Hackathon Weekend', 'Nobody sleeps, everybody claims to be building something meaningful, and the energy is contagious.', 'mixed', '{"academics": 0.25, "wellbeing": -0.25}'::jsonb, '{"study": 1.25, "work": 0.75}'::jsonb, '{"theme": "tech"}'::jsonb),
  ('PUB-021', 'Spring Sunshine', 'The weather is so unfairly nice that everyone becomes slightly easier to be around.', 'mixed', '{"social": 0.25, "wellbeing": 0.25}'::jsonb, '{}'::jsonb, '{"theme": "weather"}'::jsonb),
  ('PUB-022', 'Rainy Gloom', 'Grey skies settle over campus and motivation takes a visible hit.', 'mixed', '{"wellbeing": -0.25}'::jsonb, '{"exercise": 0.75, "socialize": 0.9}'::jsonb, '{"theme": "weather"}'::jsonb),
  ('PUB-023', 'Dining Hall Upgrade', 'The food is suspiciously edible today, which improves morale more than administration could ever understand.', 'mixed', '{"wellbeing": 0.5}'::jsonb, '{}'::jsonb, '{"theme": "food"}'::jsonb),
  ('PUB-024', 'Messy Renovation', 'Construction noise follows you from building to building and concentration loses badly.', 'mixed', '{"wellbeing": -0.25}'::jsonb, '{"study": 0.75, "rest": 0.9}'::jsonb, '{"theme": "construction"}'::jsonb),
  ('PUB-025', 'Campus Festival', 'Booths, music, and free nonsense fill the quad and make socializing much easier than normal.', 'mixed', '{"social": 0.25}'::jsonb, '{"socialize": 1.5}'::jsonb, '{"theme": "festival"}'::jsonb),
  ('PUB-026', 'Housing Email Scare', 'An alarming housing message hits every inbox and shaves a layer off everyone''s patience.', 'daily_decay', '{"wellbeing": -0.25, "money": -0.25}'::jsonb, '{}'::jsonb, '{"theme": "stress"}'::jsonb),
  ('PUB-027', 'Midnight Breakfast', 'The campus throws a cheerful late-night event and students reward it with chaos.', 'mixed', '{"wellbeing": 0.25, "money": 0.25}'::jsonb, '{"night_socialize": 1.25}'::jsonb, '{"theme": "food"}'::jsonb),
  ('PUB-028', 'Professor Office Hours Push', 'Professors suddenly insist everyone come talk to them, and some students actually benefit.', 'mixed', '{"academics": 0.25}'::jsonb, '{"class": 1.15, "study": 1.1}'::jsonb, '{"theme": "academics"}'::jsonb),
  ('PUB-029', 'Campus Gym Promo', 'The rec center starts giving out branded water bottles and students briefly buy into the illusion of balance.', 'mixed', '{"wellbeing": 0.25}'::jsonb, '{"exercise": 1.5}'::jsonb, '{"theme": "fitness"}'::jsonb),
  ('PUB-030', 'Slow Wi-Fi Day', 'Every page takes too long to load and everyone''s work rhythm turns ugly.', 'mixed', '{"academics": -0.25}'::jsonb, '{"study": 0.8, "work": 0.9}'::jsonb, '{"theme": "tech"}'::jsonb),
  ('PUB-031', 'Scholarship Deadline Buzz', 'Everybody remembers money can be won as well as lost, and ambition briefly spikes.', 'mixed', '{"academics": 0.25, "money": 0.25}'::jsonb, '{"study": 1.15}'::jsonb, '{"theme": "money"}'::jsonb),
  ('PUB-032', 'Student Protest', 'Campus gets loud, serious, and politically charged in a way that disrupts routine but energizes some people.', 'mixed', '{"social": 0.25, "wellbeing": -0.25}'::jsonb, '{"class": 0.8, "socialize": 1.15}'::jsonb, '{"theme": "activism"}'::jsonb),
  ('PUB-033', 'Merciless Humidity', 'Everything feels sticky, heavy, and one degree more exhausting than it should.', 'daily_decay', '{"wellbeing": -0.25}'::jsonb, '{"exercise": 0.75}'::jsonb, '{"theme": "weather"}'::jsonb),
  ('PUB-034', 'Bookstore Buyback Week', 'Suddenly old books have value again and students start hunting their shelves for forgotten treasure.', 'mixed', '{"money": 0.5}'::jsonb, '{"work": 1.1}'::jsonb, '{"theme": "money"}'::jsonb),
  ('PUB-035', 'Peer Tutoring Boom', 'Students help each other out more than usual, and that cooperation actually pays off.', 'mixed', '{"academics": 0.25, "social": 0.25}'::jsonb, '{"study": 1.2, "socialize": 1.1}'::jsonb, '{"theme": "community"}'::jsonb),
  ('PUB-036', 'Exam Rumor Mill', 'Everyone has heard a different version of the truth and all of them are making the mood worse.', 'mixed', '{"wellbeing": -0.25, "academics": 0.25}'::jsonb, '{"study": 1.1}'::jsonb, '{"theme": "exam"}'::jsonb),
  ('PUB-037', 'Late Bus Chaos', 'Transit starts failing in small, annoying ways that make every schedule feel less stable.', 'mixed', '{"wellbeing": -0.25}'::jsonb, '{"work": 0.9, "socialize": 0.9}'::jsonb, '{"theme": "transport"}'::jsonb),
  ('PUB-038', 'Club Recruitment Blitz', 'Every organization on campus suddenly wants your time, energy, and email address.', 'mixed', '{"social": 0.5}'::jsonb, '{"socialize": 1.25}'::jsonb, '{"theme": "clubs"}'::jsonb),
  ('PUB-039', 'Quiet Quad Day', 'Campus relaxes into a weirdly peaceful rhythm and people stop clenching their jaw for a few hours.', 'mixed', '{"wellbeing": 0.5}'::jsonb, '{"rest": 1.2}'::jsonb, '{"theme": "calm"}'::jsonb),
  ('PUB-040', 'Tech Career Night', 'Industry people descend on campus with lanyards, stress, and free tote bags.', 'mixed', '{"money": 0.25, "social": 0.25}'::jsonb, '{"work": 1.2, "socialize": 1.1}'::jsonb, '{"theme": "career"}'::jsonb),
  ('PUB-041', 'Gym Closed', 'The rec center shuts down for maintenance and everyone who relied on it is suddenly annoyed.', 'action_multiplier', '{}'::jsonb, '{"exercise": 0.0}'::jsonb, '{"theme": "fitness", "blocked": true}'::jsonb),
  ('PUB-042', 'Professor Curve Panic', 'Rumors of a class curve create hope, despair, and a lot of weird math in group chats.', 'mixed', '{"academics": 0.25, "wellbeing": -0.25}'::jsonb, '{"study": 1.1}'::jsonb, '{"theme": "academics"}'::jsonb),
  ('PUB-043', 'Night Market', 'Food stalls and student vendors make campus feel alive after dark in a way money somehow forgives.', 'mixed', '{"social": 0.25, "money": 0.25}'::jsonb, '{"night_socialize": 1.25}'::jsonb, '{"theme": "festival"}'::jsonb),
  ('PUB-044', 'Library Quiet Crackdown', 'The librarians are enforcing silence like a sacred oath, and studying benefits from the fear.', 'action_multiplier', '{}'::jsonb, '{"study": 1.25}'::jsonb, '{"theme": "academics"}'::jsonb),
  ('PUB-045', 'Campus Donation Drive', 'A feel-good event makes people unusually generous and slightly easier to connect with.', 'mixed', '{"social": 0.25, "wellbeing": 0.25}'::jsonb, '{}'::jsonb, '{"theme": "community"}'::jsonb),
  ('PUB-046', 'Frozen Pipes', 'Maintenance issues ripple through multiple dorms and the whole campus mood takes a cold hit.', 'mixed', '{"wellbeing": -0.5}'::jsonb, '{"rest": 0.85}'::jsonb, '{"theme": "weather"}'::jsonb),
  ('PUB-047', 'Exam Review Session', 'A surprisingly useful review session gets everyone a little more focused and a little less doomed.', 'mixed', '{"academics": 0.5}'::jsonb, '{"study": 1.2}'::jsonb, '{"theme": "exam"}'::jsonb),
  ('PUB-048', 'Side Hustle Craze', 'Students suddenly start selling, flipping, and freelancing everything that is not bolted down.', 'mixed', '{"money": 0.25}'::jsonb, '{"work": 1.25}'::jsonb, '{"theme": "money"}'::jsonb),
  ('PUB-049', 'Sunset Concert', 'A free outdoor show gives the evening a social boost and a brief illusion that campus life is magical.', 'mixed', '{"social": 0.25, "wellbeing": 0.25}'::jsonb, '{"night_socialize": 1.3}'::jsonb, '{"theme": "music"}'::jsonb),
  ('PUB-050', 'Deadline Compression', 'Several course deadlines seem to collapse toward the same point in time and everybody feels the squeeze.', 'mixed', '{"academics": 0.25, "wellbeing": -0.5}'::jsonb, '{"study": 1.15, "rest": 0.85}'::jsonb, '{"theme": "stress"}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  effect_type = EXCLUDED.effect_type,
  flat_stat_changes = EXCLUDED.flat_stat_changes,
  multipliers = EXCLUDED.multipliers,
  metadata = EXCLUDED.metadata;

INSERT INTO private_event_defs (
  id,
  title,
  description,
  effect_type,
  code_prefix,
  risk_payload,
  reward_payload,
  metadata
) VALUES
  ('PRIV-001', 'Secret Study Group', 'A grad student slips you an invite to a locked basement room where the most stressed people on campus quietly get ahead together.', 'risk_reward', 'STUDY', '{"wellbeing": -0.25}'::jsonb, '{"academics": 1.5}'::jsonb, '{"theme": "academics"}'::jsonb),
  ('PRIV-002', 'Underground Poker', 'A whispered invite, a cramped apartment, and a table full of students pretending they know probability better than they do.', 'risk_reward', 'POKER', '{"money": -1.0}'::jsonb, '{"money": 2.0}'::jsonb, '{"theme": "money"}'::jsonb),
  ('PRIV-003', 'VIP Concert', 'Someone with a wristband and bad judgment offers you a backstage pass and exactly one chance to be interesting.', 'risk_reward', 'VIP', '{"wellbeing": -0.25}'::jsonb, '{"social": 1.5, "wellbeing": 0.25}'::jsonb, '{"theme": "music"}'::jsonb),
  ('PRIV-004', 'Office Hours Invite', 'A professor emails you directly with the kind of subject line that could change your week for better or worse.', 'risk_reward', 'OFFICE', '{"wellbeing": -0.5}'::jsonb, '{"academics": 1.75}'::jsonb, '{"theme": "academics"}'::jsonb),
  ('PRIV-005', 'Greek Mixer', 'A handwritten invitation lands in your room and everything about it says this could go very well or very stupidly.', 'risk_reward', 'GREEK', '{"wellbeing": -0.25, "money": -0.25}'::jsonb, '{"social": 1.75}'::jsonb, '{"theme": "social"}'::jsonb),
  ('PRIV-006', 'Insider Internship', 'An advisor forwards you a job opening that does not look publicly listed anywhere, which is either excellent or suspicious.', 'risk_reward', 'INTERN', '{"academics": -0.25}'::jsonb, '{"money": 1.75, "academics": 0.5}'::jsonb, '{"theme": "career"}'::jsonb),
  ('PRIV-007', 'Dorm Rooftop Party', 'You climb somewhere you are not technically supposed to be and discover half the cool people on campus had the same idea.', 'risk_reward', 'ROOF', '{"wellbeing": -0.5}'::jsonb, '{"social": 1.5}'::jsonb, '{"theme": "social"}'::jsonb),
  ('PRIV-008', 'Questionably Legal Tutoring', 'A genius senior offers to teach you how to ace a class using methods that are academically adjacent to honest.', 'risk_reward', 'TUTOR', '{"wellbeing": -0.25, "social": -0.25}'::jsonb, '{"academics": 1.75}'::jsonb, '{"theme": "academics"}'::jsonb),
  ('PRIV-009', 'Late-Night Delivery Shift', 'A friend ropes you into a one-night cash gig that may or may not be worth the exhaustion.', 'risk_reward', 'DELIV', '{"wellbeing": -0.5}'::jsonb, '{"money": 1.75}'::jsonb, '{"theme": "money"}'::jsonb),
  ('PRIV-010', 'Secret Supper Club', 'An invite-only dinner hidden somewhere off campus promises food, conversation, and exactly the right level of mystery.', 'risk_reward', 'SUPPER', '{"money": -0.25}'::jsonb, '{"social": 1.0, "wellbeing": 1.0}'::jsonb, '{"theme": "food"}'::jsonb),
  ('PRIV-011', 'Black Market Textbooks', 'You get offered expensive books for cheap prices by somebody who definitely did not acquire them through normal channels.', 'risk_reward', 'BOOK', '{"money": -0.25, "social": -0.25}'::jsonb, '{"academics": 1.25, "money": 0.75}'::jsonb, '{"theme": "money"}'::jsonb),
  ('PRIV-012', 'After-Hours Lab Access', 'Somebody with keycard access lets you into equipment most students never get to touch.', 'risk_reward', 'LAB', '{"wellbeing": -0.25}'::jsonb, '{"academics": 1.5, "money": 0.25}'::jsonb, '{"theme": "academics"}'::jsonb),
  ('PRIV-013', 'Underground Comedy Night', 'A tiny room off campus hosts the funniest and most awkward people you have ever met in one place.', 'risk_reward', 'COMEDY', '{"social": -0.25}'::jsonb, '{"social": 1.5, "wellbeing": 0.5}'::jsonb, '{"theme": "social"}'::jsonb),
  ('PRIV-014', 'Rival Club Sabotage', 'Someone asks you to quietly help undermine another student group, and the moral math is not great.', 'risk_reward', 'RIVAL', '{"social": -0.5, "wellbeing": -0.25}'::jsonb, '{"money": 1.0, "social": 0.75}'::jsonb, '{"theme": "social"}'::jsonb),
  ('PRIV-015', 'Professor Dinner', 'A tiny dinner with faculty could become a career-defining conversation or a painfully formal waste of energy.', 'risk_reward', 'DINNER', '{"wellbeing": -0.25, "money": -0.25}'::jsonb, '{"academics": 1.0, "social": 0.75}'::jsonb, '{"theme": "career"}'::jsonb),
  ('PRIV-016', 'Hidden Art Show', 'An unmarked studio hosts an invite-only exhibit full of dramatic people, good snacks, and networking potential.', 'risk_reward', 'ART', '{"money": -0.25}'::jsonb, '{"social": 1.5, "wellbeing": 0.5}'::jsonb, '{"theme": "arts"}'::jsonb),
  ('PRIV-017', 'Finance Club Backroom', 'A small group of overconfident students claim they can teach you how to make money fast, which should concern you.', 'risk_reward', 'FIN', '{"money": -0.75}'::jsonb, '{"money": 2.0, "academics": 0.25}'::jsonb, '{"theme": "money"}'::jsonb),
  ('PRIV-018', 'Dorm Basement Cinema', 'A secret movie night turns into a low-stakes social miracle or an overlong mistake depending on your mood.', 'risk_reward', 'CINEMA', '{"academics": -0.25}'::jsonb, '{"social": 1.0, "wellbeing": 1.0}'::jsonb, '{"theme": "social"}'::jsonb),
  ('PRIV-019', 'Hidden Yoga Loft', 'A private class above an old storefront offers suspiciously effective calm if you can get there in time.', 'risk_reward', 'YOGA', '{"money": -0.25}'::jsonb, '{"wellbeing": 1.75}'::jsonb, '{"theme": "wellbeing"}'::jsonb),
  ('PRIV-020', 'Stolen Answer Rumor', 'You hear there may be leaked answers floating around, and even considering it feels like a gamble.', 'risk_reward', 'LEAK', '{"wellbeing": -0.5, "social": -0.25}'::jsonb, '{"academics": 2.0}'::jsonb, '{"theme": "academics"}'::jsonb),
  ('PRIV-021', 'Off-Campus Barista Trial', 'A cafe owner offers you a one-night paid trial shift and exactly zero patience.', 'risk_reward', 'BAR', '{"wellbeing": -0.5}'::jsonb, '{"money": 1.5, "social": 0.5}'::jsonb, '{"theme": "money"}'::jsonb),
  ('PRIV-022', 'Research Survey Farm', 'You get tipped off to a cluster of paid studies that are either easy money or deeply strange.', 'risk_reward', 'SURVEY', '{"wellbeing": -0.25}'::jsonb, '{"money": 1.25, "academics": 0.5}'::jsonb, '{"theme": "money"}'::jsonb),
  ('PRIV-023', 'Improvised Road Trip', 'A friend begs you to get in the car for one ridiculous night adventure that probably should not happen mid-semester.', 'risk_reward', 'TRIP', '{"academics": -0.5, "money": -0.25}'::jsonb, '{"social": 1.5, "wellbeing": 0.75}'::jsonb, '{"theme": "social"}'::jsonb),
  ('PRIV-024', 'Study Drug Offer', 'Somebody offers a shortcut to focus, and whether that sounds useful or alarming probably says a lot already.', 'risk_reward', 'FOCUS', '{"wellbeing": -0.75}'::jsonb, '{"academics": 1.75}'::jsonb, '{"theme": "academics"}'::jsonb),
  ('PRIV-025', 'Last-Minute House Show', 'You get invited to a tiny concert in somebody''s basement and the whole thing feels one bad speaker away from collapse.', 'risk_reward', 'SHOW', '{"wellbeing": -0.25}'::jsonb, '{"social": 1.5, "wellbeing": 0.5}'::jsonb, '{"theme": "music"}'::jsonb),
  ('PRIV-026', 'Advisor Recommendation', 'A trusted recommendation can open doors if you manage not to fumble the conversation attached to it.', 'risk_reward', 'REC', '{"social": -0.25}'::jsonb, '{"academics": 1.0, "money": 1.0}'::jsonb, '{"theme": "career"}'::jsonb),
  ('PRIV-027', 'Hidden Bookstore Buyback', 'A tiny off-campus shop quietly offers cash for books in a way the official store definitely would not.', 'risk_reward', 'BUYBACK', '{"academics": -0.25}'::jsonb, '{"money": 1.5}'::jsonb, '{"theme": "money"}'::jsonb),
  ('PRIV-028', 'Archive Room Access', 'You get shown a locked archive room with materials that make your coursework suddenly feel much more manageable.', 'risk_reward', 'ARCHIVE', '{"wellbeing": -0.25}'::jsonb, '{"academics": 1.5}'::jsonb, '{"theme": "academics"}'::jsonb),
  ('PRIV-029', 'Underground Dance Floor', 'A hidden party under a warehouse or old venue turns into either social gold or expensive dehydration.', 'risk_reward', 'DANCE', '{"wellbeing": -0.5, "money": -0.25}'::jsonb, '{"social": 1.75}'::jsonb, '{"theme": "social"}'::jsonb),
  ('PRIV-030', 'Quiet Meditation Circle', 'A tiny private mindfulness session looks cringe from the outside and suspiciously effective from the inside.', 'risk_reward', 'MEDITATE', '{"social": -0.25}'::jsonb, '{"wellbeing": 1.5, "academics": 0.25}'::jsonb, '{"theme": "wellbeing"}'::jsonb),
  ('PRIV-031', 'Risky Side Bet', 'A side wager on something stupid offers exactly the kind of odds that should make you back away, but might not.', 'risk_reward', 'BET', '{"money": -1.0}'::jsonb, '{"money": 2.0, "social": 0.25}'::jsonb, '{"theme": "money"}'::jsonb),
  ('PRIV-032', 'Illegal Parking Spot', 'A friend gives you a trick for getting somewhere faster, and the real question is whether it''s clever or cursed.', 'risk_reward', 'PARK', '{"money": -0.5}'::jsonb, '{"wellbeing": 0.5, "academics": 0.75}'::jsonb, '{"theme": "transport"}'::jsonb),
  ('PRIV-033', 'Dorm Chef Invitation', 'A self-declared culinary genius invites you to an off-menu dinner in a dorm kitchen that may or may not pass inspection.', 'risk_reward', 'CHEF', '{"money": -0.25}'::jsonb, '{"wellbeing": 1.25, "social": 0.75}'::jsonb, '{"theme": "food"}'::jsonb),
  ('PRIV-034', 'Mystery Donor Envelope', 'An anonymous envelope appears where it should not, and opening it feels morally unclear but financially tempting.', 'risk_reward', 'ENVELOPE', '{"wellbeing": -0.25}'::jsonb, '{"money": 1.75}'::jsonb, '{"theme": "money"}'::jsonb),
  ('PRIV-035', 'Basement Game Night', 'A hidden board game night promises friendship, snacks, and the possibility of spending four hours with deeply intense people.', 'risk_reward', 'GAME', '{"academics": -0.25}'::jsonb, '{"social": 1.25, "wellbeing": 0.5}'::jsonb, '{"theme": "social"}'::jsonb),
  ('PRIV-036', 'Stargazing Excursion', 'Someone talks you into driving out past the city lights and pretending existentialism counts as self-care.', 'risk_reward', 'STARS', '{"money": -0.25, "academics": -0.25}'::jsonb, '{"wellbeing": 1.5, "social": 0.5}'::jsonb, '{"theme": "wellbeing"}'::jsonb),
  ('PRIV-037', 'Short Film Shoot', 'A student filmmaker begs for help on set, and the line between glamorous and miserable is very thin tonight.', 'risk_reward', 'FILM', '{"wellbeing": -0.5}'::jsonb, '{"social": 1.0, "money": 0.75}'::jsonb, '{"theme": "arts"}'::jsonb),
  ('PRIV-038', 'Hidden Language Table', 'You find the one tiny language exchange group that is somehow both socially useful and academically relevant.', 'risk_reward', 'LANG', '{"social": -0.25}'::jsonb, '{"social": 1.0, "academics": 0.75}'::jsonb, '{"theme": "academics"}'::jsonb),
  ('PRIV-039', 'Night Lab Cleanup', 'A grad student offers you cash and access if you help with a task nobody else wants to do.', 'risk_reward', 'CLEANLAB', '{"wellbeing": -0.5}'::jsonb, '{"money": 1.25, "academics": 0.75}'::jsonb, '{"theme": "career"}'::jsonb),
  ('PRIV-040', 'Secret Donut Run', 'A late-night dessert mission offers sugar, bonding, and the chance to make tomorrow just a little harder on yourself.', 'risk_reward', 'DONUT', '{"wellbeing": -0.25}'::jsonb, '{"social": 1.0, "wellbeing": 0.75}'::jsonb, '{"theme": "food"}'::jsonb),
  ('PRIV-041', 'Shadow Interview', 'Someone arranges a private interview slot that could change your trajectory if you can hold yourself together.', 'risk_reward', 'INTERVIEW', '{"wellbeing": -0.5}'::jsonb, '{"money": 1.0, "social": 0.75}'::jsonb, '{"theme": "career"}'::jsonb),
  ('PRIV-042', 'Rooftop Study Date', 'A surprisingly romantic and productive invitation arrives with exactly enough ambiguity to be dangerous.', 'risk_reward', 'ROOFTOP', '{"social": -0.25}'::jsonb, '{"academics": 1.0, "social": 1.0}'::jsonb, '{"theme": "social"}'::jsonb),
  ('PRIV-043', 'Underground Debate Club', 'A room full of students who love hearing themselves talk may be exhausting, but it is also strangely useful.', 'risk_reward', 'DEBATE', '{"wellbeing": -0.25}'::jsonb, '{"social": 1.0, "academics": 0.75}'::jsonb, '{"theme": "academics"}'::jsonb),
  ('PRIV-044', 'Weekend Catering Gig', 'A friend-of-a-friend gets you onto an event crew for one night of chaos and cash.', 'risk_reward', 'CATER', '{"wellbeing": -0.5}'::jsonb, '{"money": 1.5, "social": 0.25}'::jsonb, '{"theme": "money"}'::jsonb),
  ('PRIV-045', 'Quiet Chapel Session', 'An invite to a silent private reflection session sounds boring until you realize your body has been begging for stillness.', 'risk_reward', 'CHAPEL', '{"social": -0.25}'::jsonb, '{"wellbeing": 1.5}'::jsonb, '{"theme": "wellbeing"}'::jsonb),
  ('PRIV-046', 'Unofficial Review Sheet', 'Someone offers a review sheet that is either heroic, unethical, or both, and you are too tired to draw the line cleanly.', 'risk_reward', 'REVIEW', '{"wellbeing": -0.5}'::jsonb, '{"academics": 1.75}'::jsonb, '{"theme": "exam"}'::jsonb),
  ('PRIV-047', 'Kitchen Hustle', 'A dorm kitchen pops up with a tiny black-market food operation and you get offered a role in it.', 'risk_reward', 'KITCHEN', '{"wellbeing": -0.25}'::jsonb, '{"money": 1.25, "social": 0.5}'::jsonb, '{"theme": "money"}'::jsonb),
  ('PRIV-048', 'Stolen Museum Pass', 'You get access to a beautiful quiet space that definitely was not intended for you tonight.', 'risk_reward', 'MUSEUM', '{"money": -0.25}'::jsonb, '{"wellbeing": 1.0, "academics": 0.75}'::jsonb, '{"theme": "arts"}'::jsonb),
  ('PRIV-049', 'Midnight Mentor Call', 'A former student offers private advice at an absurd hour, and you take it because ambition has no sleep schedule.', 'risk_reward', 'MENTOR', '{"wellbeing": -0.5}'::jsonb, '{"academics": 1.0, "money": 0.75}'::jsonb, '{"theme": "career"}'::jsonb),
  ('PRIV-050', 'Lucky Envelope Drop', 'Someone''s friend knows someone who knows someone, and suddenly a coded invitation falls right into your hands.', 'risk_reward', 'LUCKY', '{"social": -0.25, "money": -0.25}'::jsonb, '{"money": 1.0, "social": 1.0, "wellbeing": 0.5}'::jsonb, '{"theme": "mixed"}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  effect_type = EXCLUDED.effect_type,
  code_prefix = EXCLUDED.code_prefix,
  risk_payload = EXCLUDED.risk_payload,
  reward_payload = EXCLUDED.reward_payload,
  metadata = EXCLUDED.metadata;
